### PR TITLE
files: Re-arrange files to clean-up top-level folder

### PR DESCRIPTION
**Pull request by jdemel**
The top-level folder has collected a lot of files. This is an effort to move some into subfolder. We aim to continue this effort with more commits.

I'm sure this new structure is worth discussing. Maybe some files ended up int the wrong folder. Maybe some should stay in the top-level folder.

### CODE REVIEW

**Comment by marcusmueller** [comment]
hm, maybe remove the COPYING-GPL, make the COPYING contain the LGPL text in this move? (replacing it with the pure LGPL will make Github display the license as LGPL correctly)

**Comment by jdemel** [comment]
@marcusmueller Thanks for the hint.

Actually, I intend to change 2 more things.
1. Move the `Doxyfile.in` and `DoxygenLayout.xml` into the `docs/` folder with their appropriate CMake.
2. Make sure all the appropriate files have `SPDX` license identifiers.

This is in preparation for the VOLK 3.0 LGPL release.

**EDIT**
In #581 I added a more comprehensive list of things to do.

**Review by michaelld — APPROVED** [review]
LGTM

**Comment by michaelld** [comment]
@marcusmueller are you good with these changes? I think the COPYING changes are part of another PR ... and if not yet then they will be. Small-ish steps here in preparation for find 2.x & 3.0 releases ...

**Comment by marcusmueller** [comment]
Yeah, fine with me :)

**Comment by michaelld** [comment]
OK I think we're good to go here. We can always clean up things in another PR if required.

**Pull request merged**
