### PR TITLE
MinGW/MSYS2 compatibility

### PR DESCRIPTION
**Pull request by Alesha72003**
These changes will make it possible to build volk with the opensource MinGW compiler.

### CODE REVIEW

**Comment by jdemel** [comment]
Hi! Thanks for your PR. Welcome to VOLK.

First off, a technical thing. Could you sign off your commits? There's a really nice and quick explanation how to do this if you follow the DCO CI Link.

For some reason 2 CI tests fail. I suppose this needs further investigation.

Don't mind the TravisCI failure. This is probably another issue we introduced lately while TravisCI was offline for us.

**Comment by Alesha72003** [comment]
Hmm... strange. I just sign off commits.

**Comment by jdemel** [comment]
Thanks for your PR!

**Comment by jdemel** [comment]
@Alesha72003 we ran into an issue with our MinGW CI in #477 . Would you be willing to have a look at it?

**Pull request merged**
