### PR TITLE
Python 3 compatibility fixes to allow volk_modtool to import

### PR DESCRIPTION
**Pull request by ryanvolz**
This is a collection of Python 3 compatibility fixes that allow volk_modtool to be imported. I haven't tested functionality.

This also includes a fix for a build problem that I encountered when using Python 3 and '\u' appears in the string for the Python path.

### CODE REVIEW

**Comment by noc0lour** [comment]
Hi @ryanvolz, 

sorry for the long wait. Are you still interested in getting your changes in? If yes, please contact bhilburn at gnuradio.org to get a Copyright Assignment for you.

**Comment by ryanvolz** [comment]
Yeah absolutely, if the changes are still useful. I've sent the email request as directed.

**Comment by noc0lour** [comment]
The changes are definitely appreciated, I'll test with py2 & py3 to see if things will still work or if we want to have some small workarounds to have a release with both versions working.
Thanks! :)

**Comment by ryanvolz** [comment]
I know it has been a few months, but I have completed the CLA, although I'm not sure the right emails got forwarded to inform the right GNU Radio people. Let me know if there is something else I need to do.

**Comment by noc0lour** [comment]
Thanks a lot for holding out!

**Pull request merged**
