### PR TITLE
Avx512 sincos

### PR DESCRIPTION
**Pull request by fritterhoff**
As discussed in #300 and #301 an optimized way of calculating sin and cos using AVX512

### CODE REVIEW

**Comment by jdemel** [comment]
Thanks for re-opening your PRs again. 

This PR must wait on #439 to be approved and merged though. That would be our switch to DCO.

**Review by jdemel — COMMENTED** [review]
Could you run `clang-format -i --style-file` on all files to make the format checker pass. And fulfill our code formatting requirements.

**Comment by fritterhoff** [comment]
Sure ...

**Comment by jdemel** [comment]
Since TravisCI is still not up again for gnuradio/volk I pushed your commits to my repo to run all the CI:
https://travis-ci.com/github/jdemel/volk/builds/213431099
I hope this is a publicly available Link. It seems like everything still works as expected. Thanks for your contribution.

I'm aware that the GCC 4.8 fails with some CMake issue. But this issue came up with some previous commits as well. I assume it is unrelated to your PR.

**Review by michaelld — APPROVED** [review]
Nice! Good to have these in Volk!

**Comment by michaelld** [comment]
@jdemel I merged the DCO since that makes a lot of sense; this PR passes CI & the programming looks solid -- I don't have time to review the actual algorithm here, so trusting CI to do it's job :) ... if you think this PR is ready to go then please go forth with the merge. I don't know what next steps the PR author needs to be taking with respect to DCO / CLA needs ... maybe you can explain that here too for all of us to understand?

**Comment by jdemel** [comment]
@fritterhoff Thanks for your patience!

With the DCO in place, please just sign off your commits. I assume there are 6.
```
git rebase --exec 'git commit --amend --no-edit -n -s' -i HEAD~6
```
Please be careful with this command. I tend to confuse the details here for some reason. `-s` should be the correct switch in contrast to `-S` which tries to sign your commits with a GPG key. For your last 6 commits `HEAD~6` should be the correct number.

In the end, each commit message is appended by a "Signed-off by ..." message that confirms that you have the rights to merge this code. The details are in the just merged DCO file.

**Review by jdemel — APPROVED** [review]
LGTM.

CI passes. I just double checked that the AVX512 kernels are executed as well. Thus, I'd say this PR is ready to be merged. If you could just sign off your commits, I can go ahead and merge it.

**Comment by fritterhoff** [comment]
> @fritterhoff Thanks for your patience!
> 
> With the DCO in place, please just sign off your commits. I assume there are 6.
> 
> ```
> git rebase --exec 'git commit --amend --no-edit -n -s' -i HEAD~6
> ```
> 
> Please be careful with this command. I tend to confuse the details here for some reason. `-s` should be the correct switch in contrast to `-S` which tries to sign your commits with a GPG key. For your last 6 commits `HEAD~6` should be the correct number.
> 
> In the end, each commit message is appended by a "Signed-off by ..." message that confirms that you have the rights to merge this code. The details are in the just merged DCO file.

Hi,

My commits should already bei signed?

**Comment by jdemel** [comment]
I'm sorry. Yeah of course, they are already signed. Thanks!

**Comment by jdemel** [comment]
@fritterhoff I hope I can reach you here. We're in the process to relicense VOLK under LGPL cf. #492 . Would you be willing to support us and re-submit your contributions? You only need to fill in the prepared statement and get back to us with it. e.g. respond here, or send me an email jdemel@gnuradio.org, or open a PR to add yourself to the list with the statement in the commit message. Thanks!

**Comment by fritterhoff** [comment]
Hi, sorry for the delay - I forgot to do that ... should be done with #529

**Pull request merged**
