### PR TITLE
Adds CMAKE_ASM_FLAGS to arm toolchain files

### PR DESCRIPTION
**Pull request by ast**
Adds CMAKE_ASM_FLAGS to the rest of the arm_cortex_a* files.

### CODE REVIEW

**Comment by ast** [comment]
@balister, I'm not sure about `oe-sdk_cross.cmake`?

**Comment by balister** [comment]
OK, more hoops for you :) Can you put this change in a pull request with the change that removes the flags from the CMakefile. CI for the other request will fail until this change is in. And second update the ./cmake/Toolchains/arm-linux-gnueabihf.cmake toolchain file, this is the one used in Travis to test arm builds.

**Comment by ast** [comment]
What the hell Philip, first you want me to split PRs now you want me to join them :-)

Ok I will do it!

**Comment by balister** [comment]
oe-sdk_cross.cmake has an interesting problem, I need to extract flags from the CC var and pass to asm. I need to work out the long term fix.

**Comment by michaelld** [comment]
This is a subset of #273 ... yes? If so, can we close this one & just do the other one?

**Comment by michaelld** [comment]
Closing per agreement.

**Pull request closed without merging**
