### PR TITLE
cmake: Detect if cpu_features submodule is present.

### LINKED ISSUE #424: Bad/hidden error message if one has not extracted submodules
The error message is not helpful, and indeet it's not even clear than anything went wrong! The fact that it was an error is hidden in a discrete message on the third to last line, and the actual error is a couple of pages up, out of screen.

Could we change to something that's not cmake (cough, autotools, cough), or failing that, having it fail at the actual error, to make it clear that it failed, and what failed?

```
$ cmake -DCMAKE_INSTALL_PREFIX=$HOME/opt/gnuradio-3.8.1.0 ..                                                     
-- Build type not specified: defaulting to release.                                                                                         
-- Build type set to Release.                                                                                                               
-- Extracting version information from git describe...        
CMake Error at CMakeLists.txt:123 (add_subdirectory):             
  The source directory                                                
                                                                      
    /home/xxx/src/volk/cpu_features         
                                                                                                                                            
  does not contain a CMakeLists.txt file.        
                                                                      
                                                                                                                                            
--                                                                    
-- Python checking for python >= 3.4
-- Python checking for python >= 3.4 - found
--                                                                                                                                          
-- Python checking for mako >= 0.4.2            
-- Python checking for mako >= 0.4.2 - found
-- QA Testing is enabled.                                             
--   Modify using: -DENABLE_TESTING=ON/OFF
-- System profiling is disabled.
--   Modify using: -DENABLE_PROFILING=ON/OFF   
-- Compiler name: GNU
-- Architecture is not x86 or x86_64, Overruled arch 3dnow
-- Architecture is not x86 or x86_64, Overruled arch mmx                                                                                    
-- Architecture is not x86 or x86_64, Overruled arch sse
-- Architecture is not x86 or x86_64, Overruled arch sse2
-- Architecture is not x86 or x86_64, Overruled arch sse3
-- Architecture is not x86 or x86_64, Overruled arch ssse3
-- Architecture is not x86 or x86_64, Overruled arch sse4_a
-- Architecture is not x86 or x86_64, Overruled arch sse4_1
-- Architecture is not x86 or x86_64, Overruled arch sse4_2
-- Architecture is not x86 or x86_64, Overruled arch avx
-- Architecture is not x86 or x86_64, Overruled arch avx512f
-- Architecture is not x86 or x86_64, Overruled arch avx512cd
-- Compiler doesn't support NEON, Overruled arch neon
-- Compiler doesn't support NEON, Overruled arch neonv7
-- Compiler doesn't support NEON, Overruled arch neonv8
-- Available architectures: generic;hardfp;orc;norc
-- Available machines: generic_orc                                    
-- BUILD TYPE = RELEASE
-- Base cflags = -O3 -DNDEBUG  -fcx-limited-range -Wall   
-- BUILD INFO ::: generic_orc ::: GNU ::: -O3 -DNDEBUG  -fcx-limited-range -Wall 
-- Compiler Version: cc (Raspbian 8.3.0-6+rpi1) 8.3.0   
Copyright (C) 2018 Free Software Foundation, Inc.        
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-- c flags:  -fcx-limited-range -Wall;                     
-- asm flags:                                                         
-- c flags:  -fcx-limited-range -Wall;                     
-- asm flags:                                                         
-- Loading version 2.4 into constants...                    
-- Using install prefix: /home/xxx/opt/gnuradio-3.8.1.0   
-- Configuring incomplete, errors occurred!          
See also "/home/xxx/src/volk/build/CMakeFiles/CMakeOutput.log".
See also "/home/xxx/src/volk/build/CMakeFiles/CMakeError.log".
```

### PR DESCRIPTION
**Pull request by drmpeg**
Fixes https://github.com/gnuradio/volk/issues/424

### CODE REVIEW

**Review by jdemel — CHANGES_REQUESTED** [review]
Thanks for your fix! I guess I would've tested for a `cpu_features/CMakeLists.txt` instead of `cpu_features/.git`. I just checked if that would work with our release tarballs and I doubt it.
The `.git` folder is probably not present in our release tarballs.
Thus, could you change to a check against the corresponding `CMakeLists.txt` and update the message to smth like: `cpu_features/CMakeLists.txt not found. Did you forget to git clone recursively? fix with git submodule...`? That would be awesome.

**Comment by drmpeg** [comment]
Changes pushed. Checking for submodule/.git was suggested to ensure that the submodule was initialized. But I guess it doesn't really matter here.

**Review by jdemel — APPROVED** [review]
Thanks! LGTM.

**Review by michaelld — APPROVED** [review]
LGTM; thx!

**Pull request merged**
