### PR TITLE
I, Nicholas McCarthy, hereby resubmit all my contributions to the VOLK project and repository under the terms of the LGPL-3.0-or-later. My GitHub handle is namccart. My email addresses used for contributions are: namccart@gmail.com.

### PR DESCRIPTION
**Pull request by namccart**

### CODE REVIEW

**Comment by jdemel** [comment]
@namccart Thanks for your PR. Unfortunately, it is not sufficient to add your name to the list. You also need to fill out the "suggested text" to make it absolutely clear that you re-submit your contributions under LGPL.
I suggest to add this text with your details in the commit message. Thanks!

**Comment by michaelld** [comment]
I rebased to current HEAD of `main`. @namccart do you approve of the rebasing? If so, please state so and then I'll merge.

**Comment by michaelld** [comment]
Another PR went it & now there is a conflict to this PR. Please rebase this one off of the new HEAD and force push back here.

**Comment by namccart** [comment]
Hey @michaelld... Not sure if you'll get email as a result of my push, so putting in a mention, and saying hi!

**Comment by michaelld** [comment]
Got it; thx! "Hey" back to you!

**Pull request merged**
