### PR TITLE
feat: calc sin using AVX512F

### PR DESCRIPTION
**Pull request by fritterhoff**
This PR provides an implementation of an AVX512-Version for sin calculation

### CODE REVIEW

**Comment by michaelld** [comment]
@flori-uni Do you have a CLA (code license assignment) in place yet? If you don't, I'll get you the info on how to get one.

**Comment by fritterhoff** [comment]
Hi, no I don't have a CLA.

**Comment by michaelld** [comment]
Please send @bhilburn an email requesting to start the CLA process: bhilburn@gnuradio.org .

**Comment by jdemel** [comment]
@flori-uni Is there any update on the CLA?
I'd be more than happy to merge your PRs.

**Comment by jdemel** [comment]
@fritterhoff did you get frustrated with the CLA process? I'd still be very happy to merge your PRs this one as well as #300 . Would it be feasible for you to reopen your PRs if we switch to a DCO based contribution regime? In that case, you'd only need to do a `git commit -s` on your commits to sign off your commits. Basically you'd only need to say "yeah, I have the right to merge this".

**Comment by fritterhoff** [comment]
Hi @jdemel, I no longer work in the SIMD "area" so the complete CLA process would probably be too much for only those two PRs. Actually the code is an optimized version of the existing one - so the original idea is by the developers of the AVX2 versions. If this 1 to 1 optimization is covered by the licenses I'll sign off the commits.

**Comment by jdemel** [comment]
Would you mind to reopen your PRs? I'll kick off our switch from CLA to DCO and we can merge your PRs? It is still a bit cumbersome but I hope the process is way smoother.

**Comment by fritterhoff** [comment]
Ok. I'll already deleted the source repo so I can't reopen the PR. I'll try to get that fixed...

**Comment by fritterhoff** [comment]
Hope it's fine now? 😀

**Pull request closed without merging**
