### PR TITLE
Use absolute tolerances for accumulator and dot product

### PR DESCRIPTION
**Pull request by argilo**
While looking for flaky tests with `ctest --repeat until-fail:<n>`, the `qa_volk_32f_accumulator_s32f` and `qa_volk_32f_x2_dot_prod_32f` tests turned out to be flaky. Failures occur when the sum or dot product is close to zero, in which case the relative error becomes large. As with other similar kernels, I've switched these to use absolute tolerances. I took the minimum value at which tests began passing, then doubled that to leave some breathing room.

In the longer term, these tests should be switched to use a tolerance that is proportional to the vector length.

### CODE REVIEW

**Comment by argilo** [comment]
The test failure is due to #669.

**Comment by argilo** [comment]
I ran a longer `ctest --repeat until-fail:<n>`, and `volk_32fc_accumulator_s32fc` failed as well. I'll update this PR to include that, and also switch the remaining `dot_prod` kernels over to absolute tolerances since they are likely to fail the same way.

**Comment by argilo** [comment]
Updated to include `volk_32fc_accumulator_s32fc`, `qa_volk_32fc_x2_dot_prod_32fc`, and `qa_volk_32fc_x2_conjugate_dot_prod_32fc`.

I ran 100000 iterations of all five tests, and no failures occurred.

**Review by jdemel — APPROVED** [review]
LGTM

**Pull request merged**
