### PR TITLE
fix for volk_32f_8u_polarbutterflypuppet_32f

### PR DESCRIPTION
**Pull request by hcab14**
this is a PR for the 2nd commit (now removed) in https://github.com/gnuradio/volk/pull/294

### CODE REVIEW

**Review by jdemel — APPROVED** [review]
Thanks for moving this commit to its own PR. It looks good to me.

Travis CI complains about `73 - qa_volk_32fc_convert_16ic (Failed)` in 2 test runs. I wonder why this issue is triggered here. But of course, it is unrelated to your PR.

**Comment by hcab14** [comment]
> Travis CI complains about `73 - qa_volk_32fc_convert_16ic (Failed)` in 2 test runs. 

These failures occur for neon kernels.

> I wonder why this issue is triggered here. But of course, it is unrelated to your PR.

All SIMD kernels available on the CI platform are tested (for NEON using cross-compilation+qemu).

**Review by michaelld — APPROVED** [review]
LGTM; thx!

**Comment by hcab14** [comment]
> LGTM; thx!

Thank you for your constructive feedback.
CI is OK as of now :)
However there are more "flaky" kernels.

**Comment by michaelld** [comment]
Indeed. We'll all keep working on these to get them fixed up. Thanks for your work here!

**Comment by hcab14** [comment]
> > Travis CI complains about `73 - qa_volk_32fc_convert_16ic (Failed)` in 2 test runs.
> 
> These failures occur for neon kernels.
> 
I have a fix in PR https://github.com/gnuradio/volk/pull/296

**Pull request merged**
