### PR TITLE
verbose test output in case a test fails on travis

### PR DESCRIPTION
**Pull request by hcab14**

### CODE REVIEW

**Comment by n-west** [comment]
in case you didn't know ctest -V will show you all of the test output

**Comment by hcab14** [comment]
No I did not know this. I have changed `... make test` to `ctest -V`. The new commit https://github.com/gnuradio/volk/pull/163/commits/f454f0e3a273201fd34161d7c5ee62b22ec3a270 replaces the old one.

**Review by noc0lour — APPROVED** [review]
looks good, will spit out verbose output in the test infrastructure which will help debugging.

**Comment by hcab14** [comment]
I think you can close this pull request. The proposed changes in https://github.com/gnuradio/volk/pull/164 are much better

**Comment by noc0lour** [comment]
Having both (verbose test output & granual failure reports) won't hurt travis)

**Pull request merged**
