### PR TITLE
Adds neonv7 for volk_16ic_magnitude_16i

### PR DESCRIPTION
**Pull request by ast**
```
# Raspberry Pi 4
./volk_16ic_magnitude_16i_test.sh

RUN_VOLK_TESTS: volk_16ic_magnitude_16i(131071,1)
generic completed in 7.39495 ms
neonv7 completed in 2.94383 ms
Best aligned arch: neonv7
Best unaligned arch: neonv7
```

### CODE REVIEW

**Review by michaelld — APPROVED** [review]
I have no objection to adding in this Neon-specific kernel, even though I can't test it at the moment. We have to have some trust in the developers that they are doing checks on their own hardware, yes?

**Comment by hcab14** [comment]
CI uses qemu to run tests both for NEON and for NEONv8 (cross-compiled, subjobs .6 and .7). The same comment applies to these other pull requests:
https://github.com/gnuradio/volk/pull/277
https://github.com/gnuradio/volk/pull/276
https://github.com/gnuradio/volk/pull/275

**Comment by ast** [comment]
Nice!

**Review by jdemel — APPROVED** [review]
LGTM

**Pull request merged**
