### PR TITLE
ARMv7 compilation / tests with absolute tolerance

### PR DESCRIPTION
**Pull request by hcab14**
- make volk again compile on ARMv7 https://github.com/gnuradio/volk/issues/205
- `_mm*_cvtps_epi32` -> `_mm*_cvttps_epi32` in  `volk_32f_s32f_convert_32i` `volk_32f_x2_s32f_interleave_16ic` (_truncated_ float to int conversion) https://github.com/gnuradio/volk/issues/210
- added a test with an absolute tolerance for the `volk_32f_log2_32f` kernel https://github.com/gnuradio/volk/issues/210

### CODE REVIEW

**Review by noc0lour — APPROVED** [review]
Need review from someone else on the ARMv7 part. 
For the interleave kernel we might want to add to the documentation that this kernel is in truncating mode instead of rounding.

The test changes look good and reaasonable.

**Review by balister — COMMENTED** [review]
Setting the mfpu flag in CMakelists isn't a great idea. This flag should be set in a toolchain file that knows for sure if the machine you are compiling for supports neon. I need to hunt up where it is set orginally and see what is going on

**Review by balister — CHANGES_REQUESTED** [review]
Please drop the have_mfpu_neon pieces. You should enable neon using flags in the toolchain file. toolchains are hardware specific and this is the way we should handle neon detection. There is code in the cmake that tests from neon with compile time tests, so the flags must be set correctly.

**Comment by hcab14** [comment]
Hi @balister 

> Please drop the `have_mfpu_neon` pieces. You should enable neon using flags in the toolchain file. toolchains are hardware specific and this is the way we should handle neon detection.

Ok. It is done.

But note that before ARMv8 was added, VOLK, did compile natively on ARMv7 devices without using a custom toolchain and now it does not, so this should be added somewhere to the documentation.

**Comment by balister** [comment]
Sorry for the trouble. Inserting the mfpu flag likely caused trouble for the original Pi board and armv5 machines which do not have neon at. Hopefully, we are more consistent in the future.

**Comment by hcab14** [comment]
Don't worry. Anyway, testing for `have_mfpu_neon` in lib/CMakeLists.txt felt somewhat unnatural.

**Pull request merged**
