### PR TITLE
Fix random numbers

### LINKED ISSUE #688: Poor random numbers in uint tests.
https://github.com/gnuradio/volk/blob/main/lib/qa_utils.cc#L54  Contains: `float int_max = float(uint64_t(2) << (type.size * 8));`.  If `type.size` is 8, then `int_max = uint64_t(2) << 64`.  Shift a 64-bit number by 64 is undefined behavior.  It appears that gcc masks the shift amount and no shift is performed.  Thus the random numbers generated are between 0 and 2 for unsigned 64-bit numbers and -1 and 1 for signed 64-bit numbers.

This is not ideal and causes some tests to not actually exercise algorithm.  See   https://github.com/gnuradio/volk/issues/605

### PR DESCRIPTION
**Pull request by jsallay**
Resolve https://github.com/gnuradio/volk/issues/688

Note that we need to merge https://github.com/gnuradio/volk/pull/606 beforehand because the armv8 unit test fails if we fix the random numbers.

### CODE REVIEW

**Comment by argilo** [comment]
I already have a pull request open to fix this (and some other bugs in random integer generation): #677

**Review by jdemel — APPROVED** [review]
LGTM

**Comment by jdemel** [comment]
It looks like we need to decide whether we want to merge this PR or #677 . At the moment I would prefer #677 because it addresses a bit more.

@jsallay I hope you don't mind if we close this PR and merge @argilo's PR.

**Comment by argilo** [comment]
#677 does include all the improvements made here, but one small difference is that it keeps the `int16_t` range at -7 .. +7 (for now) since some tests would become flaky if it was increased to the full numeric range of `int16_t`.

**Comment by jsallay** [comment]
I don't have a problem with closing this.

**Comment by jdemel** [comment]
Alright, I'm closing this PR in favor of #677 now.

**Pull request closed without merging**
