### PR TITLE
CMAKE_ASM_FLAGS should be set in the toolchain file

### PR DESCRIPTION
**Pull request by ast**
As per discussion with @balister

### CODE REVIEW

**Review by michaelld — COMMENTED** [review]
How about in the case of "neonv7" if "ARCH_ASM_FLAGS" is not set, then set it as before. That way if someone hasn't picked a specific cmake toolchain file this code might still do something useful.

**Comment by michaelld** [comment]
This is a subset of #273 ... yes? If so, can we close this one & just do the other one?

**Comment by ast** [comment]
Yes, remove this one and merge/review #273, it's more complete.

**Comment by michaelld** [comment]
Closing per agreement.

**Pull request closed without merging**
