### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by ast**
Update README to reflect how to build on Raspberry Pi and the importance of running volk_profile

### CODE REVIEW

**Comment by ast** [comment]
@michaelld please consider this or something similar. No one understands how to build on Raspberry Pi and there are no instructions anywhere. Also people forget to run volk_profile.

**Comment by michaelld** [comment]
@ast Yeah I like this idea. We don't provide a lot of README in Volk, so putting something into the main one makes sense to me.

**Review by michaelld — APPROVED** [review]
LGTM ; we might tweak it a bit down the road for other toolchains, but hopefully this provides a starting point for ARM-based users. Thx!

**Comment by balister** [comment]
I don't see any problems with this, if you used the same toolchain for both, do you see any meaingful differences in performance?

**Comment by ast** [comment]
@balister I think so but I haven't tested, at least for some kernels Cortex A72 has hardware sqrt and if I remember correctly some other relevant functions. I guess it really depends on the compiler...

Would be interesting to bench mark.

I have noticed that the Coretex-A72 is *significantly* faster with the generic kernels and is really closing the gap between hand optimized code quite a bit...

**Review by jdemel — APPROVED** [review]
LGTM.

**Comment by michaelld** [comment]
CI doesn't matter since this is a comment change. CLA in place. Maintainers approve. Merging.

**Pull request merged**
