### PR TITLE
update to newest version of the Intel SDE

### PR DESCRIPTION
**Pull request by hcab14**
should fix the CI tests using the Intel SDE.

### CODE REVIEW

**Review by jdemel — APPROVED** [review]
LGTM

Thanks for taking care of this.

**Comment by hcab14** [comment]
> LGTM
> 
> Thanks for taking care of this.

Thx for your feedback. As you can see it's a trivial fix.

There are still CI failures, seemingly not related to VOLK `bb/*`. Are these vestigial tails related to GNURadio?

**Comment by jdemel** [comment]
The `bb/` tests are buildbot tests. Buildbot has some hiccups.

VOLK is not bundled with GNU Radio anymore but it is still part of this org. So, I wouldn't call buildbot a remnant.

**Comment by jdemel** [comment]
It's a small change to fix our CI. Merging.

**Comment by jdemel** [comment]
@hcab14 I don't know if I was able to reach you via mail about re-licensing VOLK under LGPL. So I'd like to kindly ask you to support our effort to re-license VOLK under LGPL. There's more info in #492 about that. Thanks!

**Pull request merged**
