### PR TITLE
Added MIPS support to volk_cpu.tmpl.c.

### PR DESCRIPTION
**Pull request by michael-roe**

### CODE REVIEW

**Comment by jdemel** [comment]
If we merge this PR, we enable VOLK on another architecture. We don't have any CI for that arch. Thus, we need to be clear that this is experimental.

**Review by michaelld — COMMENTED** [review]
Is the intent here to just allow building VOLK on MIPS via generic kernels? If so, can you provide the output of running `make test` (from the cmake build directory) as well as `volk_profile` run after installing (actually the file `~/.volk/volk_config`)?

**Comment by michaelld** [comment]
I'd say we should enable PPC in the same way & also tag it experimental.

**Comment by jdemel** [comment]
How and where should we communicate that MIPS support is experimental?

**Comment by jdemel** [comment]
I suggest to add a comment to the [top-level `README.md` file under Hardware architectures](https://github.com/gnuradio/volk#hardware-architectures).

**Comment by michael-roe** [comment]
Even without this patch, we can build on MIPS.

Some kernels don't work on MIPS, because of the ABI issue with complex numbers.

The intent of this patch is to get in place most of the machinery you would need in order to have kernels that make use of MIPS Application Specific Extensions. (I wanted this for an experiment, and this part of the experiment seemed of sufficiently general usefulness as to be worth upstreaming).

Documenting MIPS support as experimental seems appropriate.

**Comment by michaelld** [comment]
> top-level `README.md` file under Hardware architectures

Agreed! Maybe something like: ```Currently VOLK aims to run with optimized kernels on x86 with SSE/AVX and ARM with NEON. VOLK has experimental support for PPC and MIPS; we are happy to accept contributions to make these architectures less experimental.```

**Comment by michael-roe** [comment]
That seems ok to me. Do you want me to include that text in a revised version of this PR, or can it just go in as a separate commit?

**Comment by jdemel** [comment]
It'd be great if you made these changes. A separate commit for these changes seems appropriate.

**Comment by balister** [comment]
I'm pretty sure volk QA passes on risc-v. I've been thinking about adding qemu riscv builds to the sausage machine.

**Comment by michael-roe** [comment]
It would be good if we ran QA on risc-v.

I think it will fail because of the issue to do with passing a C++ complex as an argument to a function that expects a C complex.

**Comment by jdemel** [comment]
Merging this PR now, since #609 contains the documentation change that should make it clear that MIPS support is experimental.

**Pull request merged**
