### PR TITLE
Fixed Broken Rotator

### LINKED ISSUE #329: volk_32fc_s32fc_x2_rotator_32fc 10 dB noise in results
When testing the rotator block with a straight signal source I noticed that the volk implementation volk_32fc_s32fc_x2_rotator_32fc has almost 10 dB of noise that builds between -133 and -123 dB that is not present in the CPU-only version.  Testing Flowgraph: signal source -> throttle -> rotator -> Frequency Sink, samp_rate=2.4e6, frequency rotation 100e3.  Running on an i7-7700HQ CPU on Ubuntu 18 64-bit.  You'll see it start okay, then build, reach a peak, then "break", then start the cycle over again.

To see the difference, compile the gr-blocks/rotator_cc_impl.cc with the "#if 0" and with "#if 1" in the work function (test code looks like it's already there to flip back and forth between CPU and volk).

Just a suspicion but I saw similar behavior on GPUs with floats where the CPU is maintaining double precision accuracy but the GPU was using true IEEE spec 9 decimal point floats.  The difference in accuracy was enough to introduce similar noise.

### PR DESCRIPTION
**Pull request by ghostop14**
Fixes #329 

The non-generic rotator blocks were using incorrect loop maximums
for the outer, inner, and remainder loops that were causing
calculation issues.  This commit corrects those issues and restores
the rotator accuracy to the default 1e-6 precision.

### CODE REVIEW

**Comment by ghostop14** [comment]
Issue 329 can be linked to this PR.

**Comment by michaelld** [comment]
> Issue 329 can be linked to this PR.

done

**Comment by michaelld** [comment]
Relevant CI passes, which is always good! Have you tried specifically stressing the rotator? I think there's a discussion of how to do this somewhere in Volk github space ...

**Comment by michaelld** [comment]
The CI error is with GCC7 in `qa_volk_16ic_x2_dot_prod_16ic` ... 1-off errors again!

**Comment by ghostop14** [comment]
Yeah I noticed that.  These changes are nowhere near that code.  Had happened on a couple other PR's.  If it runs again sometimes it goes through.  I figured that wasn't on my end.

**Comment by ghostop14** [comment]
@michaelld I did a quick search and I couldn't find any past discussion.  I had done something like that when I had originally opened the linked issue.  I did run updated tests with the new kernel in GR flowgraphs.  Some very targeted rotator comparisons against old results, as well as rotating a recorded signal and all seemed well.  There's still some noise that shows up if you set the frequency y-min to like -150 and just pump a signal source into the rotator->frequency sink, but it's way better than it was before.  I'm sure that has to do with the volk tolerances mostly being good only to 1e-6 (if you set it to 1e-7 in the qa_test for all kernels, multiple existing kernels start to fail, probably why it's set to 1e-6).

**Review by jdemel — APPROVED** [review]
LGTM. Thanks for taking the time to figure out the details.

**Comment by ghostop14** [comment]
Rebased, fixed merge issues, clang-formatted my modified files, and re-pushed.  Doesn't look like CI re-ran after force push but the conflicts are resolved in the repo.

**Review by michaelld — APPROVED** [review]
LGTM; thx!

**Review by jdemel — APPROVED** [review]
LGTM. Thanks for figuring out the correct fix.

**Comment by jdemel** [comment]
2 approvals. Merging.

**Pull request merged**
