### PR TITLE
added volk_8*_convert_*f

### PR DESCRIPTION
**Pull request by xloem**
based on volk_8u_s32f_convert_32f

Signed-off-by: 0xloem <0xloem@gmail.com>

#209

original commit was dd392e9f6c17054a18175c1063a4c43457dd1bf0 ,which would ideally be in the commit history with the thread so people can learn from the past and all.

I don't actually remember this codebase, so making further changes may be hard for me, but I can probably get to them eventually.

### CODE REVIEW

**Comment by jdemel** [comment]
Your contribution is ready to be merged. We just need to rebase it. In your case `git rebase master` while your branch `8ui_convert` is active. There is one conflict in that case that needs to be resolved. The tests you register in `lib/kernel_tests.h` need to fit. I may be able to fix that and push to your branch. But I don't want to do that without prior warning.

**Comment by jdemel** [comment]
@xloem I rebased your code. You may find it [here](https://github.com/jdemel/volk/tree/8ui_convert) for the moment. It should pass CI and everything now.

**Comment by jdemel** [comment]
Hi @xloem I hope I could help with my rebase.

EDIT:
According to our CI, run against the rebased branch, [here](https://github.com/jdemel/volk/runs/2373766782?check_suite_focus=true) it seems like `8u_convert_32f` fails with Clang.

**Comment by xloem** [comment]
Hey, I have flashbacks and seizures when I try to work on this code.  If anybody values it, please take it over or restart it.

**Comment by xloem** [comment]
i'm going to close this PR so people don't think this feature is in the queue or anything.  thanks so much for your help working through it.

**Comment by xloem** [comment]
if anybody does work through this, if you could add a mention of #209 that I left open so long unaddressed, it would be kind to me, to help me know that record of people's struggles can be preserved.  the purpose of this addition was to empower parts of RTL-SDR code, and hence SDR developers without the money to afford a radio, with the same accelerated data processing used in the rest of gnuradio.

**Pull request closed without merging**
