### PR TITLE
feat: calc cos in AVX512F

### PR DESCRIPTION
**Pull request by fritterhoff**
This PR provides calculation of the cosinus values using AVX512F

### CODE REVIEW

**Comment by fritterhoff** [comment]
Anybody an idea why using _mm512_and_si512 fails?

**Comment by jdemel** [comment]
In TravisCI it fails for GCC 4.9. Am I right? 
This makes this whole thing difficult. I guess we need to figure out if we still support GCC 4.9 before we can merge this PR.
One general remark: Could you make sure all lines are below 80 characters. At least roughly.

**Comment by fritterhoff** [comment]
Jep its GCC 4.9 in Travis. 
A possible solution would be to build a "wrapper" or something like that in a if clause for GCC 4.9. 

I'll watch out for the line length :+1:

**Comment by hcab14** [comment]
The two missing functions do not point to any intrinsics but just cast `__m512` to `__m512i` and vice versa, see avx512fintrin.h

```c
extern __inline __m512i
__attribute__ ((__gnu_inline__, __always_inline__, __artificial__))
_mm512_castps_si512 (__m512 __A)
{
  return (__m512i) (__A);
}

extern __inline __m512
__attribute__ ((__gnu_inline__, __always_inline__, __artificial__))
_mm512_castsi512_ps (__m512i __A)
{
  return (__m512) (__A);
}
```

So you could do the cast just yourself and it should be ok.

**Comment by jdemel** [comment]
At this point GCC 4.9 is an ancient compiler. Only some really longlong term support distros use it. I read about SLES 11 and RHEL 6? Ubuntu 16.04 (the oldest supported one) ships with GCC 5.4.
The question really is, should we require newer compilers or allow the code to be a bit more complex.

**Comment by fritterhoff** [comment]
Maybe it makes sense to provide the missing methods in a seperate header and put a #if arround it, so it gets only included in this special case (GCC 4.9)?

Currently I'm trying to implement more and more kernels as AVX512-Version so probably I'll get some similar problems again and again

**Comment by hcab14** [comment]
You may have a look at `include/volk/volk_avx2_intrinsics.h` and create a
similar file for AVX512.

**Comment by michaelld** [comment]
Any updates on this PR?

**Comment by fritterhoff** [comment]
I'll leave the current structure and will proceed with the CLA and change it probably later.

**Comment by jdemel** [comment]
@flori-uni Is there any update on the CLA?
We start to see merge conflicts and I'd be more than happy to avoid them by merging your PRs.

**Pull request closed without merging**
