### PR TITLE
TravisCI: Update CI to bionic distro

### PR DESCRIPTION
**Pull request by jdemel**
This is a first attempt to update our Travis CI system. So far this is a WIP and I'll make more changes as soon as I can verify that this commit does not already break everything.

TravisCI Lint: https://config.travis-ci.com/explore

This commit updates `.travis.yml` to use more recent compilers, distros
and some code cleanup.

This is progress on #336

### CODE REVIEW

**Comment by jdemel** [comment]
The newest TravisCI distro is currently bionic aka Ubuntu 18.04. I would expect them to make focal aka 20.04 available soon. Until then I suggest we stick with bionic. Also, that implies we do currently not test on GCC 9 cf. #340  .

The GCC 4.8 test is the only one that still requires Boost.

Only clang 6 is currently used in tests. We can add more clang versions if this is desired.

If we could add at least one macos test, that'd we great.

**Comment by jdemel** [comment]
@michaelld do you approve this PR?

**Review by michaelld — APPROVED** [review]
LGTM

**Comment by michaelld** [comment]
All (new) CI passes. Nice to get the CI code cleaned up! Merging!

**Pull request merged**
