### PR TITLE
Neon updates

### PR DESCRIPTION
**Pull request by balister**
Passes QA on armv7 for a9 and a15 tunes. Haven't test on aarch64 yet, but I'd like to go ahead and merge sice this shouldn't regress anyone on armv7, lets volk compile for armv5 and lets people try aarch64 and fix bugs.

### CODE REVIEW

**Comment by balister** [comment]
CI fail looks bogus?

**Comment by hcab14** [comment]
Yes. It failed to download boost. Looks like this it is intermittent. Someone should restart the build.

**Comment by douggeiger** [comment]
@balister, @n-west: I can confirm this builds and runs on aarch64, and it looks like it picks up the intrinsics-based kernels just fine. Tested `volk-config` and `volk_profile` with no errors from either.
Looks good here.

**Comment by noc0lour** [comment]
I rekicked the travis build and everything looks fine on the CI.

**Comment by balister** [comment]
Any reason this isn't merged?

**Pull request merged**
