### PR TITLE
test CI

### PR DESCRIPTION
**Pull request by noc0lour**
Will it build?

### CODE REVIEW

**Comment by n-west** [comment]
yep :-) https://github.com/n-west/volk/blob/master/.travis.yml

**Comment by noc0lour** [comment]
Was just wondering about the F26 test failures in GR, but it was the nested volk qa failing :/, ubuntu 14.04 dosen't even build with volk master, which is a non issue, I think. 

https://ci.gnuradio.org/buildbot/#/builders/24/builds/6

P.S. was just wondering how hard it is to integrate volk building into the existing CI

**Comment by n-west** [comment]
https://www.youtube.com/watch?v=bVURsxuwy_E

I do intend to commit that travis-ci stuff. I guess I lost track that we had a build bot type thing.

**Comment by n-west** [comment]
The current status is that maint is waaaaaaaaay overdue on a release to the point that I psuedo-released it on my personal github, but never pushed it to github/volk. My master branch I intend to release a new major revision when I abandon libbboost as a dependency so that it's just C and some minimal python that's required to build.

**Comment by noc0lour** [comment]
Travis is fine if it works for volk. For GNU Radio travis is killing off the build because of build times.

**Comment by noc0lour** [comment]
So, the buildbot will pick up changes in volk PRs now and build & test for Ubuntu 16.04 & 14.04 & F26 which have their default compilers and tools.

**Comment by noc0lour** [comment]
It will not be displayed for now.

**Comment by noc0lour** [comment]
Adding travis to that shouldn't be an issue though.

**Pull request closed without merging**
