### PR TITLE
Add avx2 and avx512 support

### PR DESCRIPTION
**Pull request by jessica-iwamoto**
Added AVX, AVX2, FMA, and AVX512-F support to kernels and added compiler checks for AVX512-F and AVX512-CD

### CODE REVIEW

**Comment by carlesfernandez** [comment]
Awesome!

**Comment by n-west** [comment]
Wow, this looks really great! I don't think I have any AVX-512 hardware, but AFAICT at a glance the test for it, the arch, and machine generation look good. I'm going to look around for a cheap cloud machine i can run this on. What's been your impression of performance?

**Comment by jessica-iwamoto** [comment]
We've mostly just added AVX512 to the simpler kernels, and the speed up has been about 10-20% for most of them. I suspect if AVX512 was added to the more math intensive kernels the improvements would be greater

**Comment by n-west** [comment]
So this looks great. Will happily merge-- do you both have a CLA signed with GNU Radio? cc: @bhilburn

**Comment by jessica-iwamoto** [comment]
I sent the agreement signed by us (The Aerospace Corporation) to the FSF last week, so I think we're just waiting for them to sign it?

**Comment by bhilburn** [comment]
@jessica-iwamoto - Yup, it usually takes the FSF a week or so to turn them around. Let us know once you receive the fully executed CLA! =)

**Comment by hcab14** [comment]
It would be great to have continuous integration tests for the AVX2* kernels:
- qemu-3.0 can simulate a Xeon Phi processor (-cpu KnightsMill) but when using qemu-x86_64 I get error message like TCG doesn't support requested feature: ... for the CPU features which are supposed to be emulated, and the avx2* kernels do not get called in volk_profile
- [Intel SDE](https://software.intel.com/en-us/articles/pre-release-license-agreement-for-intel-software-development-emulator-accept-end-user-license-agreement-and-download) does work for me. However it cannot be automatically downloaded (license needs to be accepted manuallly), so this file would need to be hosted somewhere else.

Any opinions?

Using the Intel SDE I get one test failure:
```
RUN_VOLK_TESTS: volk_32f_8u_polarbutterflypuppet_32f(131071,1)
generic completed in 861.198ms
u_avx completed in 246.137ms
u_avx2 completed in 281.406ms
offset 16 in1: -2 in2: 0 tolerance was: 1e-06
offset 17 in1: 4 in2: 0 tolerance was: 1e-06
offset 18 in1: -4 in2: 0 tolerance was: 1e-06
offset 19 in1: -8 in2: 0 tolerance was: 1e-06
offset 20 in1: -4 in2: -0 tolerance was: 1e-06
offset 21 in1: 8 in2: 0 tolerance was: 1e-06
offset 22 in1: 8 in2: -0 tolerance was: 1e-06
offset 23 in1: -16 in2: 2 tolerance was: 1e-06
offset 24 in1: -4 in2: -0 tolerance was: 1e-06
offset 25 in1: -8 in2: -2 tolerance was: 1e-06
volk_32f_8u_polarbutterflypuppet_32f: fail on arch u_avx2
```
which may be related to the following compiler warnings:
```
/root/volk/build/lib/volk_machine_avx2_64_mmx.c:352:84: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
     {volk_32f_8u_polarbutterfly_32f_generic, volk_32f_8u_polarbutterfly_32f_u_avx, volk_32f_8u_polarbutterfly_32f_u_avx2},
                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/volk/build/lib/volk_machine_avx2_64_mmx.c:352:84: note: (near initialization for 'volk_machine_avx2_64_mmx.volk_32f_8u_polarbutterfly_32f_impls[2]')
[ 76%] Building C object lib/CMakeFiles/volk_obj.dir/volk_machine_avx512f_64_mmx.c.o
/root/volk/build/lib/volk_machine_avx512f_64_mmx.c:353:84: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
     {volk_32f_8u_polarbutterfly_32f_generic, volk_32f_8u_polarbutterfly_32f_u_avx, volk_32f_8u_polarbutterfly_32f_u_avx2},
                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/volk/build/lib/volk_machine_avx512f_64_mmx.c:353:84: note: (near initialization for 'volk_machine_avx512f_64_mmx.volk_32f_8u_polarbutterfly_32f_impls[2]')
[ 78%] Building C object lib/CMakeFiles/volk_obj.dir/volk_machine_avx512cd_64_mmx.c.o
/root/volk/build/lib/volk_machine_avx512cd_64_mmx.c:354:84: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
     {volk_32f_8u_polarbutterfly_32f_generic, volk_32f_8u_polarbutterfly_32f_u_avx, volk_32f_8u_polarbutterfly_32f_u_avx2},
                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/volk/build/lib/volk_machine_avx512cd_64_mmx.c:354:84: note: (near initialization for 'volk_machine_avx512cd_64_mmx.volk_32f_8u_polarbutterfly_32f_impls[2]')
```

[volk_32f_8u_polarbutterfly_32f_u_avx](https://github.com/jessica-iwamoto/volk/blob/add-avx2-avx512/kernels/volk/volk_32f_8u_polarbutterfly_32f.h#L210-L212) and [volk_32f_8u_polarbutterfly_32f_u_avx2](https://github.com/jessica-iwamoto/volk/blob/add-avx2-avx512/kernels/volk/volk_32f_8u_polarbutterfly_32f.h#L318-L320) have different arguments.

**Comment by noc0lour** [comment]
Looks like the AVX2 change originated before polar kernels changed their API in fcb1e4b5d81e9bd3b5bbfba8612c6d8641a1b613.

**Comment by noc0lour** [comment]
It looks like CircleCI or other CI services might support AVX2, also they might support newer OS versions than travis.

**Comment by bhilburn** [comment]
Just a heads up: we gave CircleCI a shot at DeepSig, and found it mostly to
be ineffective for our uses with a c++ and Python codebase - it's for sure
currently targeted at web devs.

It's been a few months, so it might be better, now, though.

**Comment by jessica-iwamoto** [comment]
@bhilburn @n-west Finally received the CLA from the FSF

**Pull request merged**
