### PR TITLE
Redundant argument fix

### PR DESCRIPTION
**Pull request by jdemel**
These patches aim to fix issue #141 
Fixed issues:
- Redundant argument `frame_size` was removed. Changes API -> how to proceed?
- replaced `fabs` by `fabsf`
- refactored code for better readability.

This PR should serve as a baseline for further discussion.

For now, these bulletpoints are considered nonissues:
- `calculate_max_stage_depth_for_row` without loop. Any ideas how to express this more elegantly?
- `copysignf(1.0f, la) * copysignf(1.0f, lb) * (ala > alb ? alb : ala)` is actually the exact MinSum approximation formula. It says: `sign(a) * sign(b) * min(abs(a), abs(b))`.

Since the original issue was to fix test failures with GCC7.x this PR might need more commits and discussion. Though, flushing the SIMD units between the two major loops might fix this issue as well.

### CODE REVIEW

**Comment by marcusmueller** [comment]
Um, it looks like only the very last commit (15f40d7 --> f59a9b3) was actually merged? This is confusing!

**Comment by marcusmueller** [comment]
ah, needs to be merged onto maint.

**Comment by n-west** [comment]
Oh, yea. I merged it on to master with the merge button, and never pulled it back to maint, probably because it really changes the API

**Comment by marcusmueller** [comment]
could you still do that? I've prepared a ff-mergeable branch just for you :)

**Pull request merged**
