### PR TITLE
Misc. typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3`

### CODE REVIEW

**Comment by luzpaz** [comment]
```
The following tests FAILED:
	 85 - qa_volk_32fc_s32f_magnitude_16i (Failed)
Errors while running CTest
```

https://travis-ci.org/gnuradio/volk/jobs/556013434#L2727-L2730

**Comment by luzpaz** [comment]
please review, thanks!

**Comment by jdemel** [comment]
This PR does only change typos in comments. Thus, it shouldn't have any impact on functionality.
@luzpaz why did you post a link to a failed QA test? Is this related to your PR? Thanks for your contribution.

**Comment by luzpaz** [comment]
@jdemel I don't think my commit impacts the test. I was just making sure that this PR wasn't rotting because it didn't pass the CI and gets marked X (this happens in some projects)

**Review by michaelld — APPROVED** [review]
LGTM; I'd prefer to have typos fixed when reasonable!

**Comment by michaelld** [comment]
@jdemel are you good with this PR as-is? Fixing typos in comments won't change QA / CI or any functionality, so if you're good lets get this merged.

**Comment by jdemel** [comment]
Yeah. Let's merge it.

**Pull request merged**
