### PR TITLE
volk_32f_stddev_and_mean_32f_x2: rebased and signed off on the DCO

### PR DESCRIPTION
**Pull request by Ka-zam**
This should be ready to merge.

### CODE REVIEW

**Comment by jdemel** [comment]
@Ka-zam thanks for your patience. I know we went through a full review in #322 and agreed it would be ready to merge, except we were waiting for a CLA.

Now, only 2 technical things. 
First, could you run `clang-format` with `-i -style=file` options on the files the check formatting test points out?
Second, our DCO check tells us that some commits miss a "Signed-off ..." line. As far as I can tell, only the last commit includes that line. Though, all commits must have it now.

**Comment by Ka-zam** [comment]
@jdemel I think it's OK now but I don't know why the CI builds failed all of a sudden.

**Comment by jdemel** [comment]
I'd need to double check but I assume CI fails because `ubuntu-latest` defaults to 20.04 now. Unfortunately, the whole build matrix stops if one of the individual tests fails. Specifically, the GCC8 test fails because CMake can't find GCC8. I'm confident, we can fix this.

**Comment by jdemel** [comment]
One more thing:

> 55: Test command: C:\projects\volk\lib\volk_32f_stddev_and_mean_32f_x2_test.bat "C:/projects/volk/lib/Release"
> 55: Test timeout computed to be: 10000000
> 55: RUN_VOLK_TESTS: volk_32f_stddev_and_mean_32f_x2(131071,1)
> 55: generic completed in 4.3513 ms
> 55: u_sse completed in 0.137 ms
> 55: u_avx completed in 0.1245 ms
> 55: a_sse completed in 0.115 ms
> 55: a_avx completed in 0.1031 ms
> 55: offset 0 in1: -0.00010291 in2: -0.000102896 tolerance was: 0.0001
> 55: volk_32f_stddev_and_mean_32f_x2: fail on arch u_sse
> 55: offset 0 in1: -0.00010291 in2: -0.000102896 tolerance was: 0.0001
> 55: volk_32f_stddev_and_mean_32f_x2: fail on arch a_sse
> 55: Best aligned arch: a_avx
> 55: Best unaligned arch: u_avx
>  55/134 Test  #55: qa_volk_32f_stddev_and_mean_32f_x2 ...................***Failed    0.06 sec

It looks like your code fails in our AppVeyor CI. I wonder why though. Test tolerance is higher than the values difference.

**Comment by jdemel** [comment]
I updated our CI scripts. A simple `git rebase master` should be enough to fix this CI issue.

**Review by jdemel — APPROVED** [review]
LGTM! Thanks for your contribution and patience.
@michaelld I'd say this PR is ready to be merged.

**Review by michaelld — APPROVED** [review]
LGTM; thx!

**Pull request merged**
