### PR TITLE
cmake: Remove "find_package_handle_standard_args" warning.

### PR DESCRIPTION
**Pull request by drmpeg**

### CODE REVIEW

**Comment by drmpeg** [comment]
Fixes https://github.com/gnuradio/volk/issues/387

Goes with https://github.com/gnuradio/gnuradio/pull/3781

**Comment by jdemel** [comment]
Thanks for posting this PR. From the discussion in #387 I conclude, we need to decide how we want to spell the project in terms of case. Candidates are:

- `volk`: current project name and library name.
- `Volk`: current CMake package name
- `VOLK`: Oldish package name?

As far as I can tell, we move away from `VOLK`, thus I consider this candidate to be out. Since our C prefix is `volk` it might be more consistent to go with `volk` everywhere. But currently, we go with `Volk` for CMake packages.

I'd really like to merge this PR but I assume we need to decide on that matter first.
Is there a way to introduce multiple package names? That would provide backwards compatibility.

**Comment by drmpeg** [comment]
I'm not sure if any additional changes would actually be useful (given that CMake does all kinds of conversions to all upper case and all lower case).

BTW, the purpose of this fix is to match the case of the installed file ```VolkConfig.cmake```. Another way to accomplish the same thing would have been to rename ```VolkConfig.cmake``` to ```VOLKConfig.cmake```.

**Review by jdemel — APPROVED** [review]
I'd say it improves the current situation and doesn't break things. We can merge it.

I wouldn't close #387 yet because it tackles a broader issue.

I assume we can agree that the correct spelling should be `volk` or `Volk` everywhere in the project.

**Review by michaelld — APPROVED** [review]
LGTM

**Comment by michaelld** [comment]
I agree with `volk` and `Volk` .... not `VOLK` ("screaming" as Marcus puts it so aptly)!

**Pull request merged**
