### PR TITLE
Increase rotator precision test to 1e-6

### PR DESCRIPTION
**Pull request by ghostop14**
During testing, it appeared that the rotator was showing accuracy
to 1e-5 for the avx kernel.  (the generic kernel matched the CPU
calculations well, so I don't think there's any issue there).
This shorter precision was resulting in cycling noise of
about 10dB when tested in GNU Radio with a flowgraph consisting of
signal source->throttle->rotator->frequency sink.  While the noise
starts to appear at about -100 dB it is very prominent around
-120 dB.  If the rotator is used to frequency shift very weak
satellite or radio astronomy signals, this low-level noise
could potentially manifest in the integrated data.  This PR is
suggesting considering rotator accuracy to 1e-6 to trivialize
the resulting noise.

### CODE REVIEW

**Comment by ghostop14** [comment]
This PR is the followup to issue #329 at @jdemel's recommendation to open a PR to start the conversation on rotator precision.

**Review by jdemel — CHANGES_REQUESTED** [review]
Unfortunately, this breaks CI. Thus, we can't just increase our precision requirement.
The generic and SIMD versions seem to deviate after a few undred samples. My first suggestions would be to incorporate #331 in your PR because these to issues align.
Secondly, I suggest to align the logic in all kernels. Mostly, use the normalize def variable in all kernels to renormalize after the same number of samples.
Then, test different renormalize values. According to our CI 128 instead of 512 would do the trick. I suggest this approach and I hope it becomes clear why I suggest to incorporate a solution to #331 in this PR.

Further, I suggest to update the `volk_32fc_s32fc_rotatorpuppet_32fc` to normalize `phase` as well as `phase_inc` before a call to the actual implementation. Since all reported errors appear before first renormalization, this might be an issue as well. The scalar value `std::polar(1.0f, 0.1f)` is obviously not normalized.

I hope the suggested changes get us closer to a solution. If we need to do renormalization more often,  we need to discuss how precise we need this kernel to be.

**Comment by ghostop14** [comment]
Definitely sounds reasonable that they're related.  The flowgraph described in the PR is the best (and easiest) way to see the issue.  I'll leave it to folks with the volk skillz to determine the most appropriate solution.   Unfortunately I'm out of my element in the non-generic code.

**Comment by jdemel** [comment]
I had a look at this issue and [my work](https://github.com/jdemel/volk/commit/5c43de76ee0a219e8ce9c06f5b26b8b91bfec567) so far is inconclusive.

My observations so far:
1. Make sure all input scalars are normalized -> no improvement
2. Trigger renormalization after same num_points -> no improvement
3. Lower tolerance values move the first point that breaks this bound further to the front. It is not obvious why this would happen so far.

Since SSE kernels tend to break later, approx. factor 2, maybe the
generic kernels accumulates errors faster. That's just a wild guess
though.

This does probably need a MWE that gets us closer to the root. For now, we can't just lower the tolerance value.

**Comment by ghostop14** [comment]
Agreed.  Something's going on.  I'm glad you guys are on it.

**Pull request closed without merging**
