### PR TITLE
Correct misspelling in submodule in the README.md.

### PR DESCRIPTION
**Pull request by sbehnke**
Correct the documentation about how to update the submodules in the README.md.

### CODE REVIEW

**Review by mohmmadd — APPROVED** [review]

**Review by jdemel — APPROVED** [review]
LGTM!

Thanks for your contribution!

I assume we don't need a CLA for this change. 

@michaelld should we follow GR's lead and use DCOs?

**Review by michaelld — APPROVED** [review]
LGTM; thx!

**Comment by michaelld** [comment]
We don't need a CLA for this small a change. Merging.

**Comment by michaelld** [comment]
> @michaelld should we follow GR's lead and use DCOs?

Certainly worth looking into IMHO!

**Pull request merged**
