### PR TITLE
Modern libraries for qa_utils.cc

### PR DESCRIPTION
**Pull request by carlesfernandez**
Small fixes:

* Replaced `<ctime>` library by the safer `<chrono>`
* Replaced use of `rand()` function  from `<cstdlib>` by the safer `<random>` library
* Removed non-required includes

Tested on Ubuntu => 15.04 and on macOS 10.12

### CODE REVIEW

**Comment by n-west** [comment]
I really like these changes, but think they have to wait until we are ready to require c++11 support, which is dictated by GNU Radio's support (I think 3.8 will require c++11?).

**Comment by marcusmueller** [comment]
Confirming that 3.8 will be C++11.

**Comment by noc0lour** [comment]
So best we get a release without `C++11` for GNU Radio 3.7.12 rather soonish and then switch to `C++11` if needed?

**Comment by marcusmueller** [comment]
@noc0lour @n-west exactly. I need a VOLK release this week w/o C++11 for 3.7.12, and after that, one that can contain C++11 for 3.8

**Comment by noc0lour** [comment]
Hi @carlesfernandez 

Sorry for the long hold-up. We had to sort some things out on our side. 
I went ahead and rebased your changed. If you are still interested in getting your code in-tree please contact bhilburn at gnuradio.org regarding a Copyright Assignment for your changes.

**Comment by carlesfernandez** [comment]
ok, I've started the copyright process.

**Comment by noc0lour** [comment]
Thanks a lot! :)

**Comment by carlesfernandez** [comment]
Hi @noc0lour, 

I've already got my FSF Copyright Assignment, sent to @bhilburn and @marcusmueller 

Best regards,
Carles

**Comment by noc0lour** [comment]
Hm, how are unit tests now showing off-by-one errors again?

**Comment by noc0lour** [comment]
On `master` everything works and I just rebased this PR to use the latest code there ...

**Comment by noc0lour** [comment]
Ok, some errors are still in-tree. This stuff is still good though.

**Pull request merged**
