### PR TITLE
use constants defined in stdint.h in volk_32f_s32f_convert_{8,16,32}i

### PR DESCRIPTION
**Pull request by hcab14**
https://github.com/gnuradio/volk/issues/186

### CODE REVIEW

**Review by michaelld — CHANGES_REQUESTED** [review]
LGTM .... Would you be willing add the same fixes for <kernels/volk/volk_16ic_magnitude_16i.h>?

**Comment by hcab14** [comment]
> LGTM .... Would you be willing add the same fixes for <kernels/volk/volk_16ic_magnitude_16i.h>?

Done. I had overlooked `volk_16ic_magnitude_16i`.

**Review by michaelld — APPROVED** [review]
LGTM; thx!

**Comment by michaelld** [comment]
I just tested this & it builds cleanly ... no errors (whew) and no warnings even!

**Comment by michaelld** [comment]
@jdemel what do you think?

**Review by jdemel — APPROVED** [review]
LGTM

**Pull request merged**
