### PR TITLE
same order of FP additions for (non-NEON) SIMD and the generic implementation

### PR DESCRIPTION
**Pull request by hcab14**
https://github.com/gnuradio/volk/issues/254
https://github.com/gnuradio/volk/issues/262

### CODE REVIEW

**Comment by hcab14** [comment]
Are there any comments/suggestions?

**Comment by jdemel** [comment]
This PR looks good to me.

**Comment by michaelld** [comment]
the CI test failure has nothing to do with this PR.

**Review by michaelld — APPROVED** [review]
LGTM

**Pull request merged**
