### PR TITLE
volk_32fc_index_max_16u

### PR DESCRIPTION
**Pull request by trondeau**
changed output variable from unsigned int to unsigned short to match the function name.

### CODE REVIEW

**Comment by n-west** [comment]
Seems unlikely, but does this fix https://github.com/gnuradio/volk/issues/73 ?

**Comment by trondeau** [comment]
Probably unrelated to #73.

I force updated the PR with the same fix to volk_32f_index_max_16u. However, we might want to be careful because we're iterating over an int but the target is now a short. Might need some protection against overflowing?

**Comment by n-west** [comment]
Yes, seems like this should either cast num_points to a short/uint16_t or loop on a condition like `number < MIN(num_points, USHRT_MAX)` (where the min is obviously only taken once).

Also, while we're making type consistency changes I think uint16_t is preferred over short. Grepping through existing code it doesn't seem consistent one way or the other on using stdint types, but since we explicitly list bit size in kernel names I'd like new code to use stdints.

**Comment by trondeau** [comment]
Ok, changed the data types to stdint types, fixed some issues, limiting num_points in 16u version, and added a 32u version.

Let me know if you want any of this squashed.

**Pull request merged**
