### PR TITLE
Adds toolchain file for Raspberry Pi 3 & updated Raspberry 4.

### PR DESCRIPTION
**Pull request by ast**
README.md should probably be updated with an example:

```
# Raspberry Pi 4
cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchains/arm_cortex_a72_hardfp_native.cmake ..

# Raspberry Pi 3
cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchains/arm_cortex_a53_hardfp_native.cmake ..
```

### CODE REVIEW

**Comment by michaelld** [comment]
This is great to have available for easy access and use! Is there any reasonable and reliable way to have CMake auto-determine that one of these should be selected, and then which one, such that the user can just do the usual "cmake .."? That would be ideal & awesome!

**Comment by balister** [comment]
@michaelld if there was a way for cmake to read your mind to know what the target hardware was, we wouldn't have to go to all this trouble. The alternative is runtime detection if ISA features. Compile time requires knowledge of the target hardware.

**Comment by ast** [comment]
I can't wait for the first build system that reads my mind 😂

I'd argue that if you are able to use
`cmake ..`
you are also able to use
`cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchains/arm_cortex_a72_hardfp_native.cmake ..`
it's a power user feature.

But I think it should be **clearly** documented in the README.md build examples.

**Comment by michaelld** [comment]
Ah OK yeah that all makes sense. I was going for native-builds, not cross-builds. Yes: Let's make this a power-user's feature that documented in README.md .

**Comment by ast** [comment]
@michaelld for x86 you can still just type `cmake ..` and be done with it but there are so many ARM cores the detection gets a bit tricky.

Code might build and even execute but it might not be the best version for the platform. The build system would have to build and benchmark. I guess it would be possible but it's just way more complicated.

**Comment by michaelld** [comment]
@ast understood & agreed!

**Review by michaelld — APPROVED** [review]
LGTM

**Comment by michaelld** [comment]
@jdemel what do you think about this PR?

**Comment by jdemel** [comment]
Looks good to me too. I have no experience with ARM. @ast and @balister have this experience and approve this PR. So let's merge it.

**Review by jdemel — APPROVED** [review]

**Pull request merged**
