### PR TITLE
 Fix for python3 compile issue (UnicodeDecodeError)

### PR DESCRIPTION
**Pull request by litmaj0r**
Addresses Issue #180 by forcing utf-8 encoding on the kernel_file open

### CODE REVIEW

**Comment by noc0lour** [comment]
This now fails on `py2`. Is there a way we can have it working on both?

**Comment by noc0lour** [comment]
This might actually work (:

**Comment by noc0lour** [comment]
@litmaj0r can you test with py3 if this works now? Since travis is saying yes to all py2 builds this should be safe now?

**Comment by noc0lour** [comment]
Why is this not an issue for https://github.com/gnuradio/volk/pull/189 ?

**Comment by noc0lour** [comment]
Current state compiles on py2 & py3: https://ci.gnuradio.org/buildbot/#/builders/4/builds/705 with the same setup which failed before. :tada:

**Comment by noc0lour** [comment]
@n-west Do we need Copyright Assignment from @litmaj0r for this? My changes overrode existing changes anyway so I can also close, squash and reopen a separate PR?

**Comment by marcusmueller** [comment]
@noc0lour I can't speak for @n-west, but it's below the LOC threshold we apply to the rest of GR; I'd greatly welcome if you squashed the three identically titled commits, at the very least.

**Review by mbr0wn — APPROVED** [review]

**Comment by marcusmueller** [comment]
@n-west can you please review and merge? I need to advance `next`'s submodule pointer, so that our testing infrastructure continues to work at all.

**Comment by marcusmueller** [comment]
@n-west ping. This is getting problematic!

**Pull request merged**
