### PR TITLE
Add my name to AUTHORS_RESUBMITTING_UNDER_LGPL_LICENSE.md

### PR DESCRIPTION
**Pull request by Zlika**
Signed-off-by: Zlika <zlika_ese@hotmail.com>

### CODE REVIEW

**Comment by michaelld** [comment]
@Zlika Thanks for your PR. Unfortunately, it is not sufficient to add your name to the relicense list. You also need to fill out the "[suggested text](https://github.com/gnuradio/volk/issues/492)" (bottom of the main description) to make it absolutely clear that you re-submit your contributions under LGPL. You can do this in the commit message / title or the PR message / title (though the message is preferred) or here in a comment. Thanks!

**Comment by michaelld** [comment]
@Zlika you'll need to rebase this PR, so when you do please also add the noted required text; thx!

**Comment by Zlika** [comment]
Hi @michaelld . I rebased and changed the commit message.

**Comment by jdemel** [comment]
Thanks @Zlika

**Pull request merged**
